console.log(" date code start here ")
 const now = new Date()
  console.log(now)
  console.log(now.toString())
  console.log(now.getFullYear())
  console.log(now.getMonth())
  console.log(now.getDay())
  console.log(now.getHours())
  console.log(now.getMinutes())
  console.log(now.getSeconds())

  console.log(" date code end here ")
